language: csharp
solution: OsDevKit.sln
env:
  - MONO_IOMAP=case
  - MONO_IOMAP-all
mono:
  - latest
  #- 3.12.0
  #- 3.10.0
  #- 3.8.0
#before_script:
  #- nuget Install-Package Newtonsoft.Json
  #- nuget Install-Package FCTB
branches:
  only:
    - master
git:
  submodules: false
notifications:
  email:
    recipients:
      # If you would like to be notified of build failures, add your email here
      - wordman05@gmail.com
	  - myvarhd@gmail.com
    on_success: change #[always|never|change]
    on_failure: change #[always|never|change]
